languageCode = "de"
languageName = "Deutsch"
weight = 1
title = "IIIgeley"

[params]
displayName = "DE"
isoCode = "de"
rtl = false
dateFormat = "2 January 2006"
logo = "igeley2_patch_fullsize.PNG"
secondaryLogo = "igeley2__patch_colored.PNG"
description = "Event page for the IIIgeley - a hema tournament hosted by Historisches Fechten Würzburg e.V. in Wertheim, Bavaria"
copyright = "&copy; Historisches Fechten Würzburg e.V."
