[[main]]
none = "none"

[[main]]
name = "Rules"
pageRef = "Rules"
identifier = "SNpLuzR1I9"
weight = 9999

[[main]]
name = "Team"
pageRef = "Team"
identifier = "x4a8nOSOMP"
weight = 9999

[[main]]
name = "Directions"
pageRef = "Directions"
identifier = "syU50LDaTM"
weight = 9999

[[main]]
name = "Sponsors"
pageRef = "Sponsors"
identifier = "KSGwnV5vLM"
weight = 9999

[[footer]]
none = "none"
